In [234]:
## Import modules Homework 4 Sebastian Zdarowski

import numpy as np
import pylab as pl
import pandas as pd
from sklearn.cluster import KMeans 
import os 
from sklearn import preprocessing

In [237]:
## Get working directory
os.getcwd()

'/Users/Sebastian/Graduate School/DSC - 478 Machine Learning /HW/HW 4/segmentation_data'

In [236]:
## Change working directory
os.chdir('/Users/Sebastian/Graduate School/DSC - 478 Machine Learning /HW/HW 4/segmentation_data')

In [238]:
#a.Load in the image data matrix (with rows as images and columns as features). 
#load data into PD 
segment_D = pd.read_csv("segmentation_data.txt",sep= ',', header = None)

In [239]:
segment_D.head()

0      1   2    3    4         5         6         7         8   \
0  110.0  189.0   9  0.0  0.0  1.000000  0.666667  1.222222  1.186342   
1   86.0  187.0   9  0.0  0.0  1.111111  0.720082  1.444444  0.750309   
2  225.0  244.0   9  0.0  0.0  3.388889  2.195113  3.000000  1.520234   
3   47.0  232.0   9  0.0  0.0  1.277778  1.254621  1.000000  0.894427   
4   97.0  186.0   9  0.0  0.0  1.166667  0.691215  1.166667  1.005540   

          9          10         11         12        13         14         15  \
0  12.925926  10.888889   9.222222  18.666668 -6.111111 -11.111111  17.222221   
1  13.740741  11.666667  10.333334  19.222221 -6.222222 -10.222222  16.444445   
2  12.259259  10.333334   9.333334  17.111110 -5.777778  -8.777778  14.555555   
3  12.703704  11.000000   9.000000  18.111110 -5.111111 -11.111111  16.222221   
4  15.592592  13.888889  11.777778  21.111110 -5.111111 -11.444445  16.555555   

          16        17        18  
0  18.666668  0.508139  1.910864  
1  19.222221  0.463329  1.941465  
2  17.111110  0.480149  1.987902  
3  18.111110  0.500966  1.875362  
4  21.111110  0.442661  1.863654

In [240]:
#Load Class data into PD 

segment_class = pd.read_csv("segmentation_classes.txt", header = None, sep = '\t', names = ['Class','Value'])

segment_class.head()


Class  Value
0  GRASS      0
1  GRASS      0
2  GRASS      0
3  GRASS      0
4  GRASS      0

In [312]:
#bring in segment names / load name data into PD 
segment_Name = pd.read_csv("segmentation_names.txt", header = None)

segment_Name.head()
segment_Name = segment_Name.iloc[:, 0] #just keep names 
#segment_Name

In [247]:
#Using your favorite method (e.g., sklearn's min-max scaler), perform min-max normalization 
#on the data matrix so that each feature is scaled to [0,1] range.

min_max_scaler = preprocessing.MinMaxScaler().fit(segment_D)
segmentD_norm = min_max_scaler.transform(segment_D) #normalize segment data for processing 
segmentD_norm

array([[0.43, 0.74, 0.  , ..., 0.12, 0.51, 0.83],
       [0.34, 0.73, 0.  , ..., 0.13, 0.46, 0.84],
       [0.89, 0.97, 0.  , ..., 0.11, 0.48, 0.84],
       ...,
       [0.5 , 0.62, 0.  , ..., 0.07, 0.54, 0.18],
       [0.59, 0.61, 0.  , ..., 0.08, 0.5 , 0.18],
       [0.49, 0.63, 0.  , ..., 0.1 , 0.48, 0.17]])

In [281]:
#1b) Next, Perform Kmeans clustering (for this problem, use the Kmeans implementation 
#in scikit-learn) on the image data (since there are a total 7 pre-assigned image classes, 
#you should use K = 7 in your clustering).
kmeans = KMeans(n_clusters=7, max_iter=500, verbose=1) # initialization



In [314]:
#Fit Kmeans data for segment data 
kmeans.fit(segmentD_norm)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 433.7222987613985
start iteration
done sorting
end inner loop
Iteration 1, inertia 401.4343968244699
start iteration
done sorting
end inner loop
Iteration 2, inertia 386.4458795041581
start iteration
done sorting
end inner loop
Iteration 3, inertia 374.68829717472283
start iteration
done sorting
end inner loop
Iteration 4, inertia 369.8766137016345
start iteration
done sorting
end inner loop
Iteration 5, inertia 367.50337200443363
start iteration
done sorting
end inner loop
Iteration 6, inertia 365.0985471431368
start iteration
done sorting
end inner loop
Iteration 7, inertia 361.98834299942916
start iteration
done sorting
end inner loop
Iteration 8, inertia 358.97713355811567
start iteration
done sorting
end inner loop
Iteration 9, inertia 356.14980807530156
start iteration
done sorting
end inner loop
Iteration 10, inertia 354.2850080131935
start iteration
done sorting
end inner loop
Iteration 11,

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 413.3456055272954
start iteration
done sorting
end inner loop
Iteration 1, inertia 389.51723379396867
start iteration
done sorting
end inner loop
Iteration 2, inertia 380.4425698694454
start iteration
done sorting
end inner loop
Iteration 3, inertia 376.0895347985934
start iteration
done sorting
end inner loop
Iteration 4, inertia 374.75936200654144
start iteration
done sorting
end inner loop
Iteration 5, inertia 374.5017747130637
start iteration
done sorting
end inner loop
Iteration 6, inertia 374.4392671461284
start iteration
done sorting
end inner loop
Iteration 7, inertia 374.43741433560115
start iteration
done sorting
end inner loop
Iteration 8, inertia 374.43741433560115
center shift 0.000000e+00 within tolerance 4.150157e-06
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 403.0881579045852
start iteration
done sorting
end inner loop
Iteration 1, inert

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [315]:
kmeans.labels_ #print out kmeans labels 

array([3, 3, 3, ..., 1, 1, 0], dtype=int32)

In [316]:
#show cluster centers 
print (kmeans.cluster_centers_)

[[0.25 0.39 0.   0.08 0.02 0.08 0.   0.06 0.01 0.15 0.14 0.18 0.12 0.72
  0.34 0.35 0.18 0.41 0.2 ]
 [0.77 0.43 0.   0.01 0.02 0.04 0.   0.02 0.   0.04 0.03 0.06 0.03 0.78
  0.22 0.49 0.06 0.54 0.24]
 [0.54 0.15 0.   0.03 0.   0.03 0.   0.03 0.   0.82 0.78 0.89 0.79 0.27
  0.67 0.29 0.89 0.21 0.13]
 [0.51 0.81 0.   0.08 0.01 0.05 0.   0.05 0.   0.11 0.09 0.09 0.14 0.68
  0.08 0.82 0.13 0.41 0.89]
 [0.25 0.46 0.   0.03 0.01 0.04 0.   0.03 0.   0.03 0.02 0.04 0.02 0.77
  0.22 0.51 0.04 0.8  0.18]
 [0.3  0.53 0.   0.05 0.05 0.1  0.01 0.08 0.01 0.4  0.37 0.47 0.35 0.5
  0.57 0.21 0.47 0.3  0.16]
 [0.75 0.53 0.   0.04 0.04 0.11 0.02 0.11 0.02 0.3  0.28 0.35 0.26 0.59
  0.45 0.31 0.35 0.3  0.16]]


In [317]:
print("Cluter output")
pd.DataFrame(kmeans.cluster_centers_.T, index = segment_Name,
             columns = ['C1', 'C2','C3','C4','C5',' C6','C7'])

#print out clusters results with segment names as rows 

Cluter output


C1        C2        C3        C4        C5  \
0                                                                        
REGION-CENTROID-COL   0.251212  0.769063  0.535099  0.513994  0.254150   
REGION-CENTROID-ROW   0.393366  0.425930  0.150167  0.808937  0.459382   
REGION-PIXEL-COUNT    0.000000  0.000000  0.000000  0.000000  0.000000   
SHORT-LINE-DENSITY-5  0.075397  0.014024  0.027778  0.077441  0.026437   
SHORT-LINE-DENSITY-2  0.019345  0.022654  0.001667  0.005051  0.013793   
VEDGE-MEAN            0.078009  0.039702  0.030228  0.054474  0.036790   
VEDGE-SD              0.004436  0.002983  0.000543  0.001407  0.002031   
HEDGE-MEAN            0.062256  0.023116  0.026766  0.046335  0.026610   
HEDGE-SD              0.005348  0.002094  0.000587  0.001401  0.001651   
INTENSITY-MEAN        0.147286  0.040385  0.823246  0.108790  0.025687   
RAWRED-MEAN           0.137358  0.034426  0.779716  0.091403  0.017510   
RAWBLUE-MEAN          0.184210  0.057385  0.894170  0.092414  0.041999   
RAWGREEN-MEAN         0.117524  0.028059  0.788761  0.142676  0.016247   
EXRED-MEAN            0.718395  0.779917  0.270665  0.679161  0.769281   
EXBLUE-MEAN           0.343568  0.222795  0.666373  0.079002  0.216020   
EXGREEN-MEAN          0.354664  0.486886  0.289386  0.821287  0.508631   
VALUE-MEAN            0.184522  0.058362  0.894170  0.134901  0.042910   
SATURATION-MEAN       0.414107  0.539152  0.211804  0.414491  0.803157   
HUE-MEAN              0.202772  0.244988  0.125066  0.892333  0.180407   

                            C6        C7  
0                                         
REGION-CENTROID-COL   0.302506  0.748274  
REGION-CENTROID-ROW   0.530862  0.532041  
REGION-PIXEL-COUNT    0.000000  0.000000  
SHORT-LINE-DENSITY-5  0.052260  0.039157  
SHORT-LINE-DENSITY-2  0.046610  0.037651  
VEDGE-MEAN            0.100817  0.113530  
VEDGE-SD              0.009420  0.018922  
HEDGE-MEAN            0.083972  0.107311  
HEDGE-SD              0.011043  0.017627  
INTENSITY-MEAN        0.400608  0.298573  
RAWRED-MEAN           0.370347  0.277521  
RAWBLUE-MEAN          0.472461  0.350081  
RAWGREEN-MEAN         0.353036  0.263837  
EXRED-MEAN            0.497146  0.593300  
EXBLUE-MEAN           0.570882  0.449242  
EXGREEN-MEAN          0.213054  0.311453  
VALUE-MEAN            0.472461  0.350163  
SATURATION-MEAN       0.302263  0.303047  
HUE-MEAN              0.163879  0.164359

In [318]:
from sklearn.metrics import completeness_score, homogeneity_score
completeness = completeness_score(segment_class['Class'], kmeans.labels_)
print(completeness)

0.6116744999910891


In [319]:
homogeneity = homogeneity_score(segment_class['Class'], kmeans.labels_)
print(homogeneity)

0.6099656393147241


In [320]:
#1C
from sklearn import decomposition

pca = decomposition.PCA(n_components = 6) #6 components required to caputre around 95 % varaince
Dtrans = pca.fit(segmentD_norm).transform(segmentD_norm)
np.set_printoptions(precision = 2, suppress = True)

print(Dtrans)



[[-0.69  0.53  0.25 -0.2  -0.08  0.05]
 [-0.67  0.51  0.34 -0.17 -0.04  0.06]
 [-0.71  0.77 -0.16 -0.01 -0.17  0.04]
 ...
 [-0.51 -0.13 -0.08  0.1  -0.03 -0.03]
 [-0.48 -0.09 -0.16  0.11  0.   -0.  ]
 [-0.44 -0.11 -0.05  0.15  0.02 -0.21]]


In [321]:
print(pca.explained_variance_ratio_)

#.61 + .13 +.1 +.05 +.04 +.02 Captures 95% variance within the model using 6 Components 

[0.61 0.13 0.1  0.05 0.04 0.02]


In [322]:
#1D:
#Run Kmeans again on PCA dataset 

kmeans.fit(Dtrans)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 312.07312284583537
start iteration
done sorting
end inner loop
Iteration 1, inertia 293.539057624012
start iteration
done sorting
end inner loop
Iteration 2, inertia 287.9745126554468
start iteration
done sorting
end inner loop
Iteration 3, inertia 279.7411417031375
start iteration
done sorting
end inner loop
Iteration 4, inertia 262.94953876389593
start iteration
done sorting
end inner loop
Iteration 5, inertia 258.2484134707431
start iteration
done sorting
end inner loop
Iteration 6, inertia 257.3971499892169
start iteration
done sorting
end inner loop
Iteration 7, inertia 257.0858973052684
start iteration
done sorting
end inner loop
Iteration 8, inertia 256.91129172063347
start iteration
done sorting
end inner loop
Iteration 9, inertia 256.8695504160075
start iteration
done sorting
end inner loop
Iteration 10, inertia 256.8403891619776
start iteration
done sorting
end inner loop
Iteration 11, in

Iteration 1, inertia 289.12488469045536
start iteration
done sorting
end inner loop
Iteration 2, inertia 285.4151372700846
start iteration
done sorting
end inner loop
Iteration 3, inertia 283.82150076334227
start iteration
done sorting
end inner loop
Iteration 4, inertia 279.0424123204223
start iteration
done sorting
end inner loop
Iteration 5, inertia 270.63530740242174
start iteration
done sorting
end inner loop
Iteration 6, inertia 264.2430457019128
start iteration
done sorting
end inner loop
Iteration 7, inertia 260.7239964283437
start iteration
done sorting
end inner loop
Iteration 8, inertia 258.92589390710924
start iteration
done sorting
end inner loop
Iteration 9, inertia 257.8175703575603
start iteration
done sorting
end inner loop
Iteration 10, inertia 257.4086772013441
start iteration
done sorting
end inner loop
Iteration 11, inertia 257.02135704569184
start iteration
done sorting
end inner loop
Iteration 12, inertia 256.85614091702246
start iteration
done sorting
end inner 

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [323]:
kmeans.labels_ #labels for pca k

array([3, 3, 3, ..., 4, 4, 0], dtype=int32)

In [324]:
kmeans.cluster_centers_

array([[-0.21, -0.24,  0.15,  0.06,  0.14, -0.01],
       [ 1.41,  0.09,  0.04, -0.17, -0.03, -0.01],
       [ 0.18,  0.04, -0.27,  0.18,  0.03,  0.02],
       [-0.62,  0.64,  0.2 , -0.09, -0.07,  0.01],
       [-0.51, -0.07, -0.34, -0.07,  0.08,  0.01],
       [ 0.44, -0.1 ,  0.16,  0.23, -0.05, -0.01],
       [-0.6 , -0.36,  0.11, -0.13, -0.13, -0.02]])

In [325]:
print("Cluster output")
pd.DataFrame(kmeans.cluster_centers_.T, index = ['PC 1', 'PC 2', 'PC 3', 'PC 4', 'PC 5','PC 6'],
             columns = ['C 1', 'C 2','C 3','C 4','C 5',' C 6','C 7'])



Cluster output


C 1       C 2       C 3       C 4       C 5       C 6       C 7
PC 1 -0.206271  1.414527  0.177111 -0.619289 -0.510925  0.436890 -0.600069
PC 2 -0.242695  0.087223  0.044092  0.638879 -0.066189 -0.104936 -0.355942
PC 3  0.150848  0.036765 -0.265832  0.195568 -0.339821  0.164951  0.110096
PC 4  0.057972 -0.173195  0.184535 -0.086052 -0.067825  0.234379 -0.127930
PC 5  0.135068 -0.029922  0.026774 -0.065975  0.075663 -0.046159 -0.130890
PC 6 -0.008928 -0.008973  0.024361  0.008999  0.005645 -0.007512 -0.016801

In [326]:
completeness2 = completeness_score(segment_class['Class'], kmeans.labels_)
print(completeness2)

0.6103678575178679


In [327]:
homogeneity2 = homogeneity_score(segment_class['Class'], kmeans.labels_)
print(homogeneity2)

0.6087785936973596


In [ ]:
#1E
#completeness and homgenity did not change much pre PCA and post PCA. Even though we had 6 componets, 
#felt like it was not needed to perform PCA on this dataset

In [54]:
#2A

from numpy import *
from numpy import linalg as la
import numpy as np
import os


In [51]:
#Set up Distances

def ecludSim(inA,inB):
    return 1.0 / (1.0 + la.norm(inA - inB))

def pearsSim(inA,inB):
    if len(inA) < 3 : return 1.0
    return 0.5 + 0.5 * corrcoef(inA, inB, rowvar = 0)[0][1]

def cosSim(inA,inB):
    num = float(inA.T * inB)
    denom = la.norm(inA)*la.norm(inB)
    return 0.5 + 0.5 * (num / denom)

In [52]:
def standEst(dataMat, user, simMeas, item):
    n = shape(dataMat)[1]
    simTotal = 0.0; ratSimTotal = 0.0
    for j in range(n):
        userRating = dataMat[user,j]
        if userRating == 0: continue
        overLap = nonzero(logical_and(dataMat[:,item]>0, \
                                      dataMat[:,j]>0))[0]
        if len(overLap) == 0: similarity = 0
        else: similarity = simMeas(dataMat[overLap,item], \
                                   dataMat[overLap,j])
        #print 'the %d and %d similarity is: %f' % (item, j, similarity)
        simTotal += similarity
        ratSimTotal += similarity * userRating
    if simTotal == 0: return 0
    else: return ratSimTotal/simTotal
    
def svdEst(dataMat, user, simMeas, item):
    n = shape(dataMat)[1]
    simTotal = 0.0; ratSimTotal = 0.0
    data=mat(dataMat)
    U,Sigma,VT = la.svd(data)
    Sig4 = mat(eye(4)*Sigma[:4]) #arrange Sig4 into a diagonal matrix
    xformedItems = data.T * U[:,:4] * Sig4.I  #create transformed items
    for j in range(n):
        userRating = data[user,j]
        if userRating == 0 or j==item: continue
        similarity = simMeas(xformedItems[item,:].T,\
                             xformedItems[j,:].T)
        #print 'the %d and %d similarity is: %f' % (item, j, similarity)
        simTotal += similarity
        ratSimTotal += similarity * userRating
    if simTotal == 0: return 0
    else: return ratSimTotal/simTotal

In [53]:
# This function is not needed for Assignment 4, but may be useful for experimentation
def recommend(dataMat, user, N=3, simMeas=cosSim, estMethod=standEst):
    unratedItems = nonzero(dataMat[user,:].A==0)[1] #find unrated items 
    if len(unratedItems) == 0: return 'you rated everything'
    itemScores = []
    for item in unratedItems:
        estimatedScore = estMethod(dataMat, user, simMeas, item)
        itemScores.append((item, estimatedScore))
    return sorted(itemScores, key=lambda jj: jj[1], reverse=True)[:N]

In [ ]:
## Get working directory
os.getcwd()

In [55]:
## Change working directory
os.chdir('/Users/Sebastian/Graduate School/DSC - 478 Machine Learning /HW/HW 4/jokes')

In [122]:
dataMat = genfromtxt('modified_jester_data.csv',delimiter=',')
dataMat


array([[ 3.18, 19.79,  1.34, ...,  0.  ,  0.  ,  0.  ],
       [15.08, 10.71, 17.36, ..., 11.34,  6.68, 12.07],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       ...,
       [16.58, 16.63, 15.85, ...,  0.  ,  0.  ,  0.  ],
       [ 3.67,  4.45,  3.67, ...,  3.77,  3.77,  3.28],
       [ 9.88, 11.73,  9.16, ...,  0.  ,  0.  ,  0.  ]])

In [136]:
dataMat.shape

(1000, 100)

In [95]:
jokes = load_jokes('jokes.csv') 

In [100]:
def get_joke_text(jokes, id):
	return jokes[id]

In [94]:
def load_jokes(file):
	jokes = genfromtxt(file, delimiter=',', dtype=str)
	jokes = np.array(jokes[:,1])
	return jokes

In [167]:
jokes[10]
#jokes.shape
#1A :DataSet has been loaded in

"Q. What do a hurricane a tornado and a redneck divorce all have in common? A. Someone's going to lose their trailer..."

In [135]:
xda = np.shape(dataMat)[1]
xda
#simMeas = cosSim(jokes[:,0],jokes[:,4])

100

In [146]:
# This function performs evaluatoin on a single user based on the test_ratio
# For example, with test_ratio = 0.2, a randomly selected 20 percent of rated 
# items by the user are withheld and the rest are used to estimate the withheld ratings

def cross_validate_user(dataMat, user, test_ratio, estMethod=standEst, simMeas=pearsSim):
    number_of_items = np.shape(dataMat)[1]
    rated_items_by_user = np.array([i for i in range(number_of_items) if dataMat[user,i]>0])
    test_size = test_ratio * len(rated_items_by_user) #issue is here in the code,
    test_indices = np.random.randint(0, len(rated_items_by_user), round(test_size))
    withheld_items = rated_items_by_user[test_indices]
    original_user_profile = np.copy(dataMat[user])
    dataMat[user, withheld_items] = 0 # So that the withheld test items is not used in the rating estimation below
    error_u = 0.0
    count_u = len(withheld_items)

    # Compute absolute error for user u over all test items
    for item in withheld_items:
        # Estimate rating on the withheld item
        estimatedScore = estMethod(dataMat, user, simMeas, item)
        error_u = error_u + abs(estimatedScore - original_user_profile[item])	

    # Now restore ratings of the withheld items to the user profile
    for item in withheld_items:
        dataMat[user, item] = original_user_profile[item]
        
    # Return sum of absolute errors and the count of test cases for this user
    # Note that these will have to be accumulated for each user to compute MAE
    return error_u, count_u

In [232]:
#2B Set up test function
def test(dataMat, test_ratio, estMethod):
    error=0 #control variable, set to 0 to keep count of total error
    count=0 #control variable, set to 0 to keep count of total users
    n = len(dataMat)
    
    for x in range(n):
        #standEst1 = standEst(dataMat, x, simMeas, jokes)
        
        if estMethod =="standEst":
            error_u, count_u = cross_validate_user(dataMat,x,test_ratio,estMethod = standEst,simMeas=pearsSim)
            #grab return values from cross_validate
            #dataMat, user, test_ratio, estMethod=standEst, simMeas=pearsSim
        
        if estMethod == "svdEst":
            error_u, count_u = cross_validate_user(dataMat,x,test_ratio,estMethod = svdEst,simMeas=pearsSim)
            #grab return values from cross_validate
        
        error+=error_u #sum up all errors from all test cases 
        count+=count_u #sum up total count from all users
        MAE = error/count
        #print("Round: " ,x,"err count: ",error)
    print('Mean Abosulute Error for ',estMethod," : ",MAE)
    
    
    # Write this function to iterate over all users and for each perform evaluation by calling
	# the above cross_validate_user function on each user. MAE will be the ratio of total error 
	# across all test cases to the total number of test cases, for all users
    



In [231]:
test(dataMat, 0.2, "svdEst")

Mean Abosulute Error for  svdEst  :  3.629449351033515


In [233]:
test(dataMat, 0.2, "standEst")

Mean Abosulute Error for  standEst  :  3.727182346232928


In [160]:
#use as reference / not being used 
def knn_search(instance, train, label,  K, measure):
    """ find K nearest neighbours of data point instance among train """

    if measure == 0:
        # euclidean distances from the other points
        dists = np.sqrt(((train - instance)**2).sum(axis=1))
    elif measure == 1:
        # cosine similarity
        train_norm = np.array([np.linalg.norm(train[i]) for i in range(len(train))])
        instance_norm = np.linalg.norm(instance)
        sims = np.dot(train,instance)/(train_norm * instance_norm)
        dists = 1 - sims
    idx = np.argsort(dists) # sorting

    # returns the predicted class and top K neighbors of kNN
    clslbl = (label[1][idx[:K]])
    if (clslbl == 1).sum() == (clslbl == 0).sum():
        pred_cls = '?'
    elif (clslbl == 1).sum() > (clslbl == 0).sum():
        pred_cls = 1
    else:
        pred_cls = 0

    top_K_neighbors = train[idx[:K]]


In [333]:
def print_most_similar_jokes(dataMat, jokes, queryJoke, k, metric=pearsSim):
    print ('Joke that we are starting out with: \n', jokes[queryJoke]) #print out starting joke 
    #Above prints out joke associated with joke number
    n = shape(dataMat.T)[0] #transform dataMat to get proper length of all jokes
    J = dataMat.T #get columns
    
    tempList = [] #hold values for KNN distances
    
    for x in range(n):
        distance=metric(J[queryJoke], J[x])
        dist=[distance, x]
        tempList.append(dist)
    tempList.sort() #sort list so we get most similar results first 
    #grab top 5 jokes from list 
    tempList = tempList[:k] #keep only 5 best 
    
    print (k,'Top Recommended jokes are: ')
    print("___________________________________________________")
    for x in range(len(tempList)):
        jokeNum = int(tempList[x][1]) 
        simJoke = jokes[tempList[x][1]]
        print ('Joke #', jokeNum,simJoke) #print out each similar joke 
        print('___________________________________________________')
    return tempList


 #Write this function to find the k most similar jokes (based on user ratings) to a queryJoke
	# The queryJoke is a joke id as given in the 'jokes.csv' file (an corresponding to the a column in dataMat)
	# You must compare ratings for the queryJoke (the column in dataMat corresponding to the joke), to all
	# other joke rating vectors and return the top k. Note that this is the same as performing KNN on the 
    # columns of dataMat. The function must retrieve the text of the joke from 'jokes.csv' file and print both
	# the queryJoke text as well as the text of the returned jokes.
    
    



In [334]:
output_jokes = print_most_similar_jokes(dataMat, jokes, 4, 5,pearsSim)

Joke that we are starting out with: 
 Q. What's O. J. Simpson's Internet address? A.	Slash slash backslash slash slash escape.
5 Top Recommended jokes are: 
___________________________________________________
Joke # 0 A man visits the doctor. The doctor says "I have bad news for you.You have cancer and Alzheimer's disease". The man replies "Well thank God I don't have cancer!"
___________________________________________________
Joke # 1 This couple had an excellent relationship going until one day he came home from work to find his girlfriend packing. He asked her why she was leaving him and she told him that she had heard awful things about him. "What could they possibly have said to make you move out?" "They told me that you were a pedophile." He replied "That's an awfully big word for a ten year old."
___________________________________________________
Joke # 59 What did the Buddhist say to the hot dog vendor?Make me one with everything.
_____________________________________________